name: run api testing
on:
    push:
        branches: [main]
permissions:
  checks: write
  contents: read
jobs:
    api-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.11.0]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: API testing
              run: npm test
            
            - name: API testing generate results .xml file
              run: npm run test:report

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()
              with:
                files: |
                  test-results/**/*.xml
